name: e2e sync
run-name: testing out GitHub Actions 🚀
on:
  push:
    branches: [main, k8s-sync-*]
jobs:
  post-job-script:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🔎 The name of your branch is ref:${{ github.ref }} and your repository is ${{ github.repository }}."
  
  post-job-script-2:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🔎 The name of your branch is ref-name:${{ github.ref_name }} and your repository is ${{ github.repository }}."
  
  sync-vcluster:
    name: Sync-vcluster-repo
    needs: [
      post-job-script,
      post-job-script-2
    ]
    runs-on: ubuntu-latest
    if: ${{ always() && !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled') && contains(github.ref, 'k8s-sync') && (github.event_name == 'push')}} 
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Run Sync script
        run: |
          echo "Running sync script ${{ github.ref }}"
          scripts/sync.sh
  
  notification:
    name: team-notification
    needs: [sync-vcluster]
    runs-on: ubuntu-latest
    if: ${{ always() && contains(github.ref, 'k8s-sync')}}
    steps:
      - name: notification
        run: |
          echo "successaa"
